### ISSUE TITLE
year 2000

### ISSUE THREAD

**Issue by diefans** [zeburon/sailfish-solarsystem#1]
the actual date is shown with a 2-digit year. if the time runs longer, there is an overflow...

**Comment by zeburon** [comment]
I will probably have to specify a custom date string format. On my phone it displays "03/03/2015" whereas the emulator seems to use a different locale with "03 Mar 2015"

**Comment by zeburon** [comment]
fixed in v1.2
the date format is now always dd-MMM-yyyy.
I might make it configurable at some point.
